language: java
jdk: oraclejdk11


cache:
  directories:
  - $HOME/.m2

before_deploy:
- openssl aes-256-cbc -K $encrypted_4f0d00631887_key -iv $encrypted_4f0d00631887_iv
  -in .travis/gpg.asc.enc -out .travis/gpg.asc -d
